SwissDataScienceCenter/amalthea

- controller/templates/statefulset.yaml
This PR removes the service IPs from the user pod envs.
> Remove service links

- CHANGELOG.md
- helm-chart/amalthea/Chart.yaml
- helm-chart/chartpress.yaml
> chore: prep 0.1.3 release

- controller/k8s_resources.py
- controller/templates/statefulset.yaml
- tests/unit/test_k8s_resources.py
As discussed. Hopefully the last time we touch the probes.
> fix(app): failing probes for rstudio

- controller/k8s_resources.py
- controller/templates/statefulset.yaml
> fix(app): failing probes for anonymous sessions

- CHANGELOG.md
- helm-chart/amalthea/Chart.yaml
- helm-chart/chartpress.yaml
I think it is def worth making a release out of this even though it is one bug.
> chore: prep 0.2.1 release

- .github/workflows/tests.yaml
- helm-chart/amalthea/templates/scheduler/configmap.yaml
- helm-chart/amalthea/templates/scheduler/deployment.yaml
- helm-chart/amalthea/templates/scheduler/rbac.yaml
- utils/chart_rbac/__init__.py
* Give a name to the scheduler
* Fix required RBAC for the scheduler to work properly
> fix(helm-chart) Fix scheduling through optional scheduler.

- Dockerfile
- Pipfile
- Pipfile.lock
- controller/config.py
- controller/metrics.py
- controller/server_controller.py
- controller/utils.py
- helm-chart/amalthea/templates/deployment.yaml
- helm-chart/amalthea/templates/networkpolicies.yaml
- helm-chart/amalthea/values.schema.json
- helm-chart/amalthea/values.yaml
> feat(app): expose metrics to prometheus 

- .github/workflows/generate-crd-docs.yaml
This should make renkubot show up properly as the author/committer.
> chore(ci): show renkubot as committer

- CHANGELOG.md
- helm-chart/amalthea/Chart.yaml
- helm-chart/chartpress.yaml
> chore: prep 0.5.1 release

- CHANGELOG.md
- helm-chart/amalthea/Chart.yaml
- helm-chart/chartpress.yaml
> chore: prep 0.6.0 release

- CHANGELOG.md
- helm-chart/amalthea/Chart.yaml
- helm-chart/chartpress.yaml
> chore: prep 0.7.0 release

- helm-chart/amalthea/crd-spec.yaml
- helm-chart/amalthea/templates/rbac/_rbac_rules.tpl
The full feature is implemented in #344
> feat: update CRD to support session hibernation

- CHANGELOG.md
- Pipfile.lock
- acceptance-tests/package-lock.json
- helm-chart/amalthea/Chart.yaml
- helm-chart/chartpress.yaml
New release and package updates
> chore: prep release 0.8.0 and update packages

- CHANGELOG.md
> chore: prep 0.10.0 release

- CHANGELOG.md
- helm-chart/amalthea/Chart.yaml
> chore: prep  0.11.0 release

- api/v1alpha1/amaltheasession_children.go
- api/v1alpha1/amaltheasession_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/amalthea.dev_amaltheasessions.yaml
- internal/controller/amaltheasession_controller_test.go
This PR implements two things:
- Adding a /dev/shm volume to the StatefulSet
- The option to adjust /dev/shm in the CRD
Closes #630
> feat: implement shm support

- controller/config.py
- controller/main.py
- helm-chart/amalthea/templates/deployment.yaml
The way that the controller is started was changed. But the ingesting of configuration values for which namespaces should be watched was not fully updated.
> fix: properly pass down namespace configuration

- CHANGELOG.md
- helm-chart/amalthea/Chart.yaml
- pyproject.toml
Just to keep the changelog and versions up to date.
> chore: prep 0.12.1 release

- .github/workflows/publish-chart.yaml
- CHANGELOG.md
- controller/main.py
- helm-chart/amalthea/Chart.yaml
- pyproject.toml
Also adds changelog for a new bugfix release.
> fix: broken metrics auditlog config

- .github/workflows/publish-chart.yaml
- .github/workflows/tests.yaml
- Makefile
- helm-chart/amalthea-sessions/templates/amaltheasession-crd.yaml
The automated templating of the CRD was missing a proper end for the if statement.
I fixed this and added the helm lint commands to run in the tests and before publishing.
> fix: amalthea-sessions helm chart bad if statement

- internal/authproxy/serve.go
Fixes the authentication for anonymous sessions
> fix: do not authenticate authproxy healthcheck

- api/v1alpha1/amaltheasession_types.go
- config/crd/bases/amalthea.dev_amaltheasessions.yaml
- helm-chart/amalthea-sessions/templates/amaltheasession-crd.yaml
This PR add support for retrieving AmaltheaSession objects using a short name.
Fixes #785
> feat: add short name to retrieve AmaltheaSession objects

- .github/workflows/acceptance-tests.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy-pr.yaml
- .github/workflows/generate-crd-docs.yaml
- .github/workflows/publish-chart.yaml
- .github/workflows/tests.yaml
> chore: update renku actions to 1.16.0

- internal/controller/children.go
/deploy renku=release-0.68.0 renku-data-services=fix-session-sync
> fix: update tolerations/affinity/nodeselector/priorityclass when resource class is changed

- .devcontainer/devcontainer.json
- api/v1alpha1/auth_templates.go
> fix: remove extra auth container
