SwissDataScienceCenter/amalthea

controller/k8s_resources.py, controller/templates/configmap.yaml, controller/templates/ingress.yaml, controller/templates/secret.yaml, controller/templates/service.yaml, controller/templates/statefulset.yaml, examples/oidc.yaml, helm-chart/amalthea/templates/crd.yaml, tests/unit/test_manifest_auth.py
This PR removes traefik and used the oauth2 proxy as a proxy and not just as forwardAuth middleware for traefik. As a side-effect of this, we also remove the custom authorization plugin which used to check if the `userId` added to the request by the oauth2 proxy matches the userId given as part of the JupyterServer spec. Instead, we rely on the built-in oauth2 proxy options, which are specifying a list of allowed Emails (read from the "email" claim) and/or a list of allowed groups (read from the "groups" claim). The CRD thus changes as part of this PR.
=> Remove traefik

controller/templates/configmap.yaml, controller/templates/statefulset.yaml
This time the probes actually work... I've decided to go for the `jupyter notebook list` command and use it to check for a running server at port 8888. Note that this seems to work independent on wether the server was launched through `jupyter notebook` or `jupyter lab`.
=> Fix broken jupyter container probes

acceptance-tests/cypress/integration/jupyterlab.spec.js, acceptance-tests/test.js
It turns out cypress was failing on any unhandled exception in the ui. In this case it was some plugin missing in jupyterlab.
We dont really care about this as long basic functionality works - which it does.
The problem was that the error could not properly propagate to the logs in the action.
=> chore: prevent cypress from failing on unhandled exceptions in the ui

.github/workflows/tests.yaml
Should fix the failing workflows from PRs that are not part of the SDSC org. There is no need to login to the renku docker repo to push images for testing.
=> chore(tests): do not push docker images to renku repo when doing tests

.github/workflows/acceptance-tests.yaml, controller/templates/statefulset.yaml
So it seems that rstudio returns 404 even if everything is ok but the request to it does not contain a `User-Agent` header so that it looks like the request is coming from a browser.
This made our k8s probes fail for no real reason.
Adding this to the header of the probes solves the problem.
Currently deployed at tasko.dev.renku.ch. I also tested that it does not mess up the probes for regular jupyterlab images.
If you want to test with a rstudio project, there is a public one here: https://tasko.dev.renku.ch/projects/tasko.olevski/test-r-1
This is the discourse post that helped: 
https://community.rstudio.com/t/opening-rstudio-using-aws-ssl-certificate/22006/20
=> fix(app): faililng k8s probes for rstudio

helm-chart/amalthea/templates/networkpolicies.yaml
So removing the port section out of the egress network policy makes all ports available. And we do not have to specify ranges. With this change all egress, as long as it is directed to stuff outside of the cluster, regardless of which port/protocol it is, is allowed.
closes https://github.com/SwissDataScienceCenter/renku-notebooks/issues/798
Tested this on tasko.dev.renku.ch:
Hitting an external service on port 2222 works
```
curl empty-tasko.iac.dev.renku.ch:2222 -v
*   Trying 86.119.40.248:2222...
* TCP_NODELAY set
* Connected to empty-tasko.iac.dev.renku.ch (86.119.40.248) port 2222 (#0)
> GET / HTTP/1.1
> Host: empty-tasko.iac.dev.renku.ch:2222
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Received HTTP/0.9 when not allowed
* Closing connection 0
curl: (1) Received HTTP/0.9 when not …
```
=> fix(chart): allow egress to any port out of cluster

CHANGELOG.md, helm-chart/amalthea/Chart.yaml, helm-chart/chartpress.yaml
So because we have a new feature as well we go to `0.2.0`?
We can also just bump to `0.1.4` instead of going up to `0.2.0`.
=> chore: prep 0.2.0 release

Pipfile, Pipfile.lock, controller/utils.py
ipython has a vulnerability and should not really be there as dev dependency in my opinion.
=> chore: remove ipython as dev dependency

helm-chart/amalthea/crd-spec.yaml
K8s allows numbers (interpreted as bytes) for memory/disk size.
However in the CRD we ask the user to specify disk size and then pass that on to PVC or emptyDir specs. But the CRD limits this only to strings.
With this we accept both strings and numbers.
I did some tests locally to ensure that PVCs and emptyDirs will accept the values - and they do.
=> fix: allow number or string for disk size in CRD

controller/server_controller.py, controller/utils.py
Some recent issues were possibly related to this.
It was never confirmed whether this would have helped or not. But it is still a good idea to use the API group if available to avoid confusion and problems in the future.
I checked the python k8s client and when the group is not passed in to the `resource.get` function it defaults to `None`
=> fix(app): use group in dynamic k8s client

tests/integration/conftest.py, utils/chart_rbac/__init__.py
The operator runs in a subprocess during the integration tests.
The problem is that once the operator is shut down then any outstanding jupyterservers cannot be cleaned up. And I did not realize that the subprocess where the operator was running was actively (and immediately) picking up the Ctrl-C of a cancelled test. This makes total sense in retrospect.
Now that the Ctrl-C signal is ignored, the operator can run long enough so that things are cleaned up. Even when tests are cancelled.
I also tested that the cleanup happens properly when a test fails or when an error occurs in one of the tests.
=> fix(test): cleanup of k8s resources in fixtures

Dockerfile, controller/templates/statefulset.yaml, helm-chart/amalthea/values.yaml
Run the amalthea operator as non-root.
Adds non-root users to session containers as well as setting `allowPrivilegeEscalations` to false.
closes #153
=> chore: run as non-root

.github/CODEOWNERS
The current branch protection rules require approval from a code owner so that PRs can be merged.
Renku-python should be in this list.
=> chore: add renku-python as code owners

controller/server_controller.py
Unschedulable sessions can eventually get scheduled and things will resolve themselves. But in practice we have seen this rarely happen. Therefore instead of introducing a new status for now we will try to use the failed status for unschedulable sessions.
If we see that this is confusing or needs to be changed we can add a new status in the future. It would be nicer and simpler to keep the number of statuses low IMO.
=> chore: make unschedulable sessions result in failed status

controller/server_controller.py
The pod that runs the session can (and usually does) get into an unschedulable state for a short period when it is created. This happens just before the PVC is fully provisioned. Because of this the session gets into a failed state for a short period and then goes back to "starting" when the PVC is provisioned.
In order to avoid this case the unschedulable state that occurs because of PVCs not being provisioned is ignored.
=> fix(app): avoid temporary fail state when starting

controller/config.py, controller/culling.py, controller/metrics.py, controller/server_controller.py, controller/utils.py, helm-chart/amalthea/templates/rbac/_rbac_rules.tpl, tests/integration/conftest.py, tests/integration/test_culling.py, utils/chart_rbac/__init__.py
Modifies the existing metrics from #143 and adds the rest of the metrics that were note initially implemented.
To avoid counting and also therefore potentially double-counting the number of active sessions all such metrics were removed. The number of active sessions can be estimated by looking at the differences between session launches and shutdowns.
If the number of active sessions is tracked then we need some way of tracking which sessions have been counted or not to avoid double counting. Also we need to be able to track when initializing the metric whether the sessions that are initially there have been counted or not.
With https://github.com/SwissDataScienceCenter/renku-notebooks/issues/1069 the proper and long term storage of detailed metrics will be designed and resolved.
closes …
=> feat(app): add and modify prometheus metrics

CHANGELOG.md, helm-chart/amalthea/Chart.yaml, helm-chart/chartpress.yaml
New release - just updates the helm chart version, changelog and chartpress file.
=> chore: prep 0.4.0 release

.gitignore, helm-chart/amalthea/Chart.yaml, helm-chart/amalthea/requirements.yaml, helm-chart/amalthea/templates/deployment.yaml, helm-chart/amalthea/values.schema.json, helm-chart/amalthea/values.yaml
To properly do idle session culling amalthea needs to send a get request to `https://<ful_session_path>/api/status`.
In cases where self signed certificates are used this would fail without injecting these in amalthea.
=> chore: add custom CA certificate injection

.github/workflows/generate-crd-docs.yaml
Because I added a certificates chart as a dependent for amalthea now the action that updates the rendered amalthea manifests was failing because a simple `helm dep update` was required.
See the passing action here: https://github.com/SwissDataScienceCenter/amalthea/runs/7183741988?check_suite_focus=true
This is the failing action from before: https://github.com/SwissDataScienceCenter/amalthea/runs/7182146311?check_suite_focus=true
=> Fix manifest generation

controller/templates/statefulset.yaml
It is best to not fall too far behind. This also has some additional/better control over oidc setup and parameters.
=> chore: update oauth2proxy to 7.3.0

controller/metrics/prometheus.py
closes #186 
The default bucket values are so low that they are useless. I had hopes that maybe prometheus automatically assigns buckets based on the values it sees but it make sense that this is not the case.
=> fix: buckets for prometheus histogram metrics

controller/config.py, controller/server_controller.py
The `on.create` handler gets repeated indefinitely if the handler function fails. This was causing some metrics from the handler to be published multiple times.
Now with this change the handlers for metrics are separated from the rest. And in addition the metrics are published only when the status of the server changes. So there is no chance that the same metric (for the exact same status change) will be published more than once.
closes #185
=> fix: do not publish same metric more than once

.github/workflows/acceptance-tests.yaml, acceptance-tests/test.js
I think we may have been having some issues with the last few PRs and the acceptance tests... I am not 100% sure the acceptance tests actually ran.
It is related to this: https://github.com/cypress-io/cypress/issues/19967
Hopefully an update to a new action will fix this.
=> chore(ci): update cypress action to v4

CHANGELOG.md, helm-chart/amalthea/Chart.yaml, helm-chart/chartpress.yaml
New release. 
The most important update is fixes to the metrics published by Amalthea.
=> chore: prep 0.5.2 release

controller/config.py, controller/server_controller.py
I think when I added this (originally to the notebook service) I misunderstood what "lastState" meant. 
What it truly means is that when a container is for example killed for consuming too much memory, then the last state will show "OOMKilled" as the reason and it will show the last exit code.
So with the old logic when a container was "OOMKilled" (i.e. restarted for consuming memory above its limit) then it would have it's last state as that. And the logic for the container state would be stuck on "failing" even though the new current state is all good and the whole sessions is functioning normally.
fixes https://github.com/SwissDataScienceCenter/renku-notebooks/issues/1225
=> fix(app): do not use previous status for state

controller/templates/configmap.yaml
Allow showing hidden files in the JupyterLab file browser.
=> chore: allow showing hidden files

.gitignore, controller/server_controller.py
We seem to have some sessions that never get culled that show this type of "activity" as published by jupyter lab:
```
Normal  Logging  12m   kopf  Timer 'cull_idle_jupyter_servers' succeeded.
Normal  Logging  8m5s  kopf  Timer 'cull_pending_jupyter_servers' succeeded.
Normal  Logging  7m1s  kopf  Timer 'cull_idle_jupyter_servers' succeeded.
Normal  Logging  7m1s  kopf  Checking idle status of session lorena-2eb-hs22-0bfa3903, idle seconds: 0, cpu usage: 37.767173m, server status: {'connections': -2, 'kernels': 1, 'last_activity': datetime.datetime(2022, 11, 18, 16, 31, 16, 185075, tzinfo=tzutc()), 'started': datetime.datetime(2022, 11, 15, 15, 1, 27, 848584, tzinfo=tzutc())}, age: 6568507.59917 seconds
Normal  Logging  3m5s  kopf  Timer 'cull_pending_jupyter_servers' succeeded.
Normal …
```
=> fix(app): consider idle when connections are < 0

controller/templates/statefulset.yaml
This should address https://github.com/SwissDataScienceCenter/renku-notebooks/issues/1510
Simply from the logs of 7.4.0 and 7.3.0 you can see that in 7.3.0 the watcher reloads all the time:
Log with 7.3.0
```
[2023/07/13 11:56:57] [validator.go:28] using authenticated emails file /etc/oauth2-proxy/authorized-users.txt
[2023/07/13 11:56:57] [watcher.go:80] watching /etc/oauth2-proxy/authorized-users.txt for updates
[2023/07/13 11:56:57] [provider.go:55] Performing OIDC Discovery...
[2023/07/13 11:56:57] [providers.go:145] Warning: Your provider supports PKCE methods ["plain" "S256"], but you have not enabled one with --code-challenge-method
[2023/07/13 11:56:57] [proxy.go:89] mapping path "/sessions/tasko-2eol-test-2d17-5687dfbe/sidecar/" => upstream …
```
=> chore: update oauth2 proxy to 7.4.0

CHANGELOG.md, helm-chart/amalthea/Chart.yaml, helm-chart/chartpress.yaml
New release with a minor bug fix for the restarting oauth2 proxy.
=> chore: prep 0.7.1. release

controller/server_controller.py, tests/integration/test_culling.py
Clear hibernation annotations in Amalthea instead of notebooks service to avoid flickering in the UI.
=> fix(app): clear hibernation annotation when resuming

CHANGELOG.md, helm-chart/amalthea/templates/deployment.yaml, helm-chart/amalthea/templates/scheduler/configmap.yaml, helm-chart/amalthea/templates/scheduler/deployment.yaml, helm-chart/amalthea/templates/scheduler/rbac.yaml, helm-chart/amalthea/values.schema.json, helm-chart/amalthea/values.yaml
closes #369 
Also it simplifies the  helm chart values. This way if you want our default packing scheduler you flip on the enabled flag. 
If you need more control you have to deploy your own and pass the scheduler name.
=> fix(chart): adapt scheduler for new k8s versions

controller/server_status.py
This is a small fix for a rare bug that Flora noticed.
Basically what could happen is that when you hibernate a session that is failed sometime the function that was modified below would flip the status back to "Failed" but the status should stay "Hibernated".
This fixes the problem.
=> fix: status can only be hibernated when server is hibernated

.github/workflows/acceptance-tests.yaml, controller/server_status.py
Newer versions of k8s have different pod statuses and this is causing a problem.
```
{"message": "Handler 'update_server_state' failed with an exception. Will ignore.", "exc_info": "
Traceback (most recent call last):\n  
File \"/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py\", line 276, in execute_handler_once\n
result = await invoke_handler(\n  
File \"/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py\", line 371, in invoke_handler\n    
result = await invocation.invoke(\n  
File \"/usr/local/lib/python3.9/site-packages/kopf/_core/actions/invocation.py\", line 139, in invoke\n    
await asyncio.shield(future)  # slightly expensive: creates tasks\n  
File \"/usr/local/lib/python3.9/concurrent/futures/thread.py\", line 58, in run\n   
result = …
```
=> fix: parse unknown or new k8s pod conditions

helm-chart/amalthea/values.schema.json, helm-chart/amalthea/values.yaml
They might interfere with what is set downstream, e.g.
if the admins do not want to set a limit for CPU (which
is a best practice).
=> chore: Remove default resources requests and limits.

helm-chart/amalthea/values.yaml
As the former is no longer available.
=> fix: Change the default registry to pull kube-scheduler from.

controller/crds/amaltheasession.yaml
This PR implements the new AmaltheaSession CRD.
The goal of the this new session is to give user the option to use other development environments than just JupyterLab.
New Docker images as well as instructions will be created as well as part of the implementation.
=> feat(crd): AmaltheaSession definition

helm-chart/amalthea/templates/networkpolicies.yaml, helm-chart/amalthea/values.schema.json, helm-chart/amalthea/values.yaml
Allows a user to customize his network according to internal needs
In case a user have another network with private Ips that needs to be reached, this allow the user to deploy a more custom networkpolicy for more flexibility
=> feat(networkpolicies): customize cluster IPs

api/v1alpha1/amaltheasession_children.go, config/rbac/role.yaml, internal/controller/amaltheasession_controller.go, internal/controller/amaltheasession_controller_test.go
This PR implements secrets adoption where secrets used for AmaltheaSession will get deleted when the session itself is deleted.
Following discussion, the method selected is through a finalizer.
Closes #632 
=> feat: implement secret adoption

api/v1alpha1/amaltheasession_children.go, go.mod, go.sum, internal/controller/cull.go
This PR implements authentication for registered users in a similar fashion as Amalthea's v1 using oauth2-proxy.
As a drive-by fix, it modifies the culling handling to avoid re-triggering the reconcile loop if the pod is missing.
Closes #614 
=> feat: implement authentication through oauth2proxy

api/v1alpha1/amaltheasession_types.go
omitempty triggers a strange behaviour: even if enabled is set to false in the CRD yaml, it will get the default value on initial apply call.
Using the optional markers keeps the CRD definition but without that unexpected behaviour.
Related to #614 and #637
=> fix(crd): use optional in place of omitempty for authentication.enabled

.github/workflows/publish-chart.yaml
This was failing because we do not use pipenv anymore to install things but the setup python action was setup to cache a pipenv virtualenv.
See https://github.com/SwissDataScienceCenter/amalthea/actions/runs/10263017074/job/28394359782 for failing job
=> chore(ci): fix chart publish step

CHANGELOG.md, controller/main.py, helm-chart/amalthea/Chart.yaml, pyproject.toml
After changing how some of the internal kopf code is organized I accidentally turned off the health check endpoint.
Now it is back on.
=> fix: kopf healthcheck

api/v1alpha1/amaltheasession_children.go, api/v1alpha1/amaltheasession_types.go, config/crd/bases/amalthea.dev_amaltheasessions.yaml, internal/controller/amaltheasession_controller.go, internal/controller/children.go
The status for amalthea sessions takes a long time to show up. This should address this problem.
=> fix: requeue without delay if the status is changing

api/v1alpha1/amaltheasession_children.go, cloner/cmd/clone.go, cloner/cmd/enum_flag.go
This PR implements strategies about acting before cloning.
There are three strategies:
- default: do as usual and git clone
- notifexists: don't clone if the target folder already exists
- overwrite: delete the target folder before cloning
This happens before trying to clone anything.
The goal is to allow restarting the session which means also the init container and not fail the cloning if it already happened before.
As a drive by cleanup, the `.git` extension is removed if part of the URL as happen when using the git command.
Part of: #612
=> feat(cloner): clone strategies

internal/controller/children.go, internal/controller/status.go
This PR reduces the number of requests done to the metrics endpoint and lowers the amount of log generated.
The metrics server does not create metrics data until after 10 seconds of pod container lifetime hence requesting them as soon as the pod is created will only show error message for missing pods from the metrics API.
The same goes for the idleness detection, once it was established that a pod is idle, there's no need to further log that it is is idle.
Part of #616
=> feat: quieter idleness

api/v1alpha1/amaltheasession_types.go, bundle/manifests/amalthea.dev_amaltheasessions.yaml, config/crd/bases/amalthea.dev_amaltheasessions.yaml, helm-chart/amalthea-sessions/templates/amaltheasession-crd.yaml
It is a pretty annoying typo. I completely missed it.
=> fix: typo in reconcile strategy field in CRD

api/v1alpha1/amaltheasession_types.go, api/v1alpha1/auth_templates.go, bundle/manifests/amalthea.dev_amaltheasessions.yaml, config/crd/bases/amalthea.dev_amaltheasessions.yaml, helm-chart/amalthea-sessions/templates/amaltheasession-crd.yaml
We found this after deploying. We need to priority class to enforce quotas.
Without the resource requests set for the oauth2 proxy we cannot schedule if there is a quota.
=> fix: auth resources and missing priority class

api/v1alpha1/amaltheasession_children.go
I did all of the required changes in #771 except for applying the priority class in the statefulset.
=> fix: set the priority class in the statefulset

internal/controller/amaltheasession_controller_test.go, internal/controller/children.go
Some status fields - most notably, the timestamps that indicate how long the session has been failing, hibernated or idle should be cleared after hibernation or resuming. If this is not done then one cannot successfully resume the session after hibernation (for example).
=> fix: clear status after hibernating or resuming

internal/controller/children_conditions.go, test/e2e/general_test.go
Information related to image pulling errors were lost in the original implementation because not all related cases related were handled the same.
Now the original error message is passed back in all cases.
Part of #751
=> refactor: improve error reporting with regard to image pulling

internal/controller/children.go, test/e2e/general_test.go, test/utils/utils.go
This PR refactors the handling of unschedulable pods and propagate the information back to the AmaltheaSession.
There are multiple possible reasons for pods not to be scheduled:
- Resource requests outside of system capabilties
- Topological reason (i.e. no nodes matching the selector desired)
As a drive by cleanup, the handling of the helm chart and external resources has also been improved to:
- Allow multiple runs
- Ignore not found resources when deleting
=> feat: improve unschedulable error report

api/v1alpha1/amaltheasession_children.go, bundle/manifests/amalthea.clusterserviceversion.yaml, bundle/manifests/amalthea.dev_amaltheasessions.yaml, cmd/amalthea/main.go, config/manager/kustomization.yaml, config/rbac/role.yaml, helm-chart/amalthea-sessions/templates/manager-rbac.yaml, internal/controller/amaltheasession_controller.go, internal/controller/children.go, internal/controller/cull.go, internal/controller/status.go, test/e2e/general_test.go, test/utils/utils.go
trying to "Owns()" events doesn't work, you don't get stateful set events..
The current solution works, though might have performance implications due to fetching events for each statefulset in the reconcile loop.
The status on a session would look like:
```
status:
conditions:
- lastTransitionTime: '2025-03-07T09:35:12Z'
message: The session is hibernated
reason: Hibernated
status: 'False'
type: Ready
- lastTransitionTime: '2025-03-06T09:30:28Z'
message: The ingress is setup and operational
reason: IngressOperational
status: 'True'
type: RoutingReady
containerCounts: {}
error: Quota exceeded
idle: false
initContainerCounts: {}
state: Failed
url: https://renku-ci-am-895.dev.renku.ch/sessions/john-doe-01adadc97abf/lab/
```
=> feat: surface quota exceede errors on crd

api/v1alpha1/amaltheasession_children.go, api/v1alpha1/amaltheasession_types.go, bundle/manifests/amalthea.dev_amaltheasessions.yaml, config/crd/bases/amalthea.dev_amaltheasessions.yaml, helm-chart/amalthea-sessions/templates/amaltheasession-crd.yaml
Adds a new field to the CRD.
The default is `IfNotPresent` because  that is what we had hardcoded before in the code - so this way we remain compatible.
=> feat: add image pull policy to the CRD

api/v1alpha1/amaltheasession_types.go, bundle/manifests/amalthea.dev_amaltheasessions.yaml, config/crd/bases/amalthea.dev_amaltheasessions.yaml, helm-chart/amalthea-sessions/templates/amaltheasession-crd.yaml
I thought if I just use the struct from the official k8s client it would turn into an enum magically but it will not. I was missing an kubebuilder comment to make this happen.
=> fix: make image pull policy an enum

bundle/manifests/amalthea.clusterserviceversion.yaml, config/rbac/role.yaml, helm-chart/amalthea-sessions/templates/manager-rbac.yaml, internal/controller/amaltheasession_controller.go
The rbac rules in the helm chart are not automatically updated. I opened an issue for this. For now I updated/synced them manually.
=> fix: missing mismatched rbac rules

Makefile, helm-chart/amalthea-sessions/crds/amaltheasession.yaml, helm-chart/amalthea-sessions/templates/manager-rbac.yaml, helm-chart/amalthea-sessions/values.yaml, helm-chart/amalthea/crds/jupyterserver.yaml, helm-chart/amalthea/templates/rbac/_rbac_rules.tpl, helm-chart/amalthea/values.schema.json, helm-chart/amalthea/values.yaml
This PR refactors the CRD deployment part of the amalthea and amalthea-session helm charts.
The management of the CRD, while looking simple, is in fact quite complex in its consequences.
Hence we will follow the current recommendation of the Helm maintainers.
More information about the reasoning can be found at:
https://github.com/helm/community/blob/main/hips/hip-0011.md
The RBAC cleanup will also allow for deployment on OpenShift.
=> refactor:crd deployment

Makefile, helm-chart/amalthea-sessions/templates/amaltheasession-crd.yaml, helm-chart/amalthea-sessions/values.yaml, helm-chart/amalthea/templates/crd.yaml, helm-chart/amalthea/values.schema.json, helm-chart/amalthea/values.yaml
This partially reverts commit a6bd2a4ade4991eff96e5a49bc2b47f268fb461a.
The things that are not reverted and are left in are changes to the rbac role. For some reason openshift was really pick about combining multiple api groups in one role stanza.
=> fix: revert "refactor:crd deployment (#952)"

api/v1alpha1/auth_templates.go
This is because bitnami is deprecating all free images.
=> fix: use bitnami legacy for oauth2 proxy image

internal/controller/children.go
PR stack:
* (base) #984
* #991
* #997
* #1001
* #1005 
* (this) #1006
This PR addresses an issue where the `WSTUNNEL_SECRET` used for remote sessions was being overwritten during each reconciliation loop. This behavior leads to problems for remote sessions leveraging Firecrest on a distant system:
**Secret Mismatch**: The `WSTUNNEL_SECRET` is generated by Firecrest on the remote system (e.g., Slurm) to secure the tunnel connection. If Amalthea regenerates and overwrites this secret during a reconciliation loop, it creates a mismatch between the secret known to the Kubernetes pod and the secret on the remote system. This can lead to a broken tunnel connection and an unusable remote session.
**Solution:**
The fix is implemented in `internal/controller/children.go` within the `Reconcile` …
=> Fix: Preserve `WSTUNNEL_SECRET` during reconciliation to prevent session disruption
